---
layout: essay
type: essay
title: First Impressions on JavaScript and Athletic Programming
date: 2017-01-20
labels:
  - Software Engineering
  - Learning
  - JavaScript
---



I have very limited experience in all programming languages, having only been exposed to Java and more recently C and JavaScript. Most of my time coding has been spent using Java, which pretty much means, it’s my only point of reference. My knowledge of Java is really helpful sometimes in understanding the nature of how coding languages works at the basic level, but there are times where I find myself trying to using syntax that works in Java, but not so much in Javascript. I’ve come to realize, that I need to put in a lot more time working with Javascript before it starts coming naturally to me. Working through the basic JavaScript modules was helpful in familiarizing me with the syntax of Javascript. My experience so far with JavaScript is mostly positive, I certainly like it better than Java. I like the ease in how you create variables, I don’t even need to assign types, as JavaScript seems to accept different types without exactly specifying. Debugging in Java, I would occasionally find typing errors. It’s also interesting to see that you can create variables that are functions. I’m not quite sure yet how to implement this, but it does seem useful and convenient. I don’t feel like I’m capable of making any decisions on how good or bad JavaScript is, from a software engineering perspective for a variety of reasons. Mainly, I haven’t done much software engineering in any language, but also I have only been exposed to JavaScript for about a week now, and that’s hardly enough time to form an opinion. I can say that I am looking forward to learning a new programming language, and I hope that I become proficient enough by the end of the semester to use it confidently. 

Athletic software engineering seems like a good way to learn. Before changing my major to ICS, I was majoring in Second Language Studies. One of the things they teach, is the idea of learning how to learn. Finding techniques and methods that work when you’re a student as well as when you’re teaching. Personally, I can stress over things only up to a certain point, but once I get past that point, I’m usually pretty calm. I do find the challenge of figuring out a solution to the WOD to be fun, it’s like finally solving a puzzle that you’ve been working on. I almost feel anticipation when we are about to start a WOD, just to see what’s in store. The WOD’s are helpful in getting me to think about how to implement the code before actually typing anything out. I have the habit of trying to type as I go, and that usually leads to having problems in the code as well as not knowing where exactly the problem lies. The WOD’s so far have been simple, but I find myself struggling to finish them on the first attempt. Mainly because, I’m still new in using the language and don’t know much of the syntax. Moving forward, I really need to focus on the basics, in order to correctly implement the code during the WOD’s. I think the WOD’s will be useful in improving the time it takes me to solve problems and finish projects in the future. 
